var noms = [
    "Michel Varuk",
    "Jim Carrey",
    "Albert Einstein",
    "Vivaldi",
    "Emma Watson",
    "Renaud",
    "Eminem",
    "Paul Kudd",
    "Jacques",
    "Bernadette",
    "Johnny Depp",
    "The Rock",
    "Léa",
    "Nina",
    "Julien Lepers",
    "Hugh Jackmann",
    "Jacquie",
    "Michel",
    "Gotaga",
    "Philipe",
    "HP Lovecraft",
    "Bill gates"
];

var Objets = [
    "Ordinateur",
    "Telephone Portable",
    "Montre",
    "Dé à coudre",
    "Décapsuleur",
    "Ballon de foot",
    "Clavier",
    "Pièce",
    "Marteaux",
    "Lunette de soleil",
    "Sabre",
    "Cuillère",
    "Fourchette",
    "Tasse",
    "Manette",
    "Avion",
    "Vélo"
];

var Temperature = [
    "+10°",
    "+30°",
    "+37,2",
    "-5°",
    "-50°",
    "+5°",
    "+22°",
    "+69°",
    "+18°",
    "+37°",
    "+25°",
    "+40°",
    "+28°",
    "+24°",
    "+70°"
];

var Lieux = [
    "Floyon",
    "Wignehies",
    "Barcelona",
    "Paris",
    "Tokyo",
    "Reykjairk",
    "Bondy",
    "Rio de Janiero",
    "Mons",
    "Trélon",
    "Big Ben",
    "Mont Fuji",
    "Palais de l'élysée",
    "Mairie de Paris",
    "Macdo",
    "KFC",
    "Burger King",
    "Montcuq",
    "Chute de Niagara",
    "Hide Park"
];

var Verbe = [
    "Etre",
    "Developper",
    "Jouer",
    "Coder",
    "Copier",
    "Coordonner",
    "Nager",
    "Monter",
    "Aimer",
    "Soulever",
    "Evaluer",
    "Voter",
    "Arnaquer",
    "Manger",
    "S'envoyer",
    "Enfournir",
    "Accomplir",
    "Communiquer"
];